import argparse
import re
from collections import Counter

def get_options():
    description = "Calculate token frequency across population"
    parser = argparse.ArgumentParser(description=description,
                                        prog='python calc_gene_frequency.py')
    IO = parser.add_argument_group('Input/options.out')
    IO.add_argument('--outpref',
                    default="comparisons",
                    help='Output prefix. Default = "comparisons"')
    IO.add_argument('--infile',
                    required=True,
                    help='Path to tokenised genome data .txt file.')
    IO.add_argument('--absolute-IDs',
                    action="store_true",
                    default=False,
                    help='Use absolute gene IDs to calculate frequency, combining forward and reverse strand genes.')
    IO.add_argument('--annotations',
                    default=None,
                    help='Path to annotated tokens generated by annotate_tokens.py.')
    return parser.parse_args()

def main():
    options = get_options()
    infile = options.infile
    outpref = options.outpref
    absolute_IDs = options.absolute_IDs
    annotations = options.annotations

    annotation_dict = {}
    annotation_count_dict = {}
    # get token annotations
    if annotations != None:
        with open(annotations, "r") as f2:
            while True:
                line = f2.readline()
                if not line:
                    break
                line = line.rstrip()
                split_line = line.split("\t")
                token = int(split_line[1])

                annotation_dict[token] = line
                annotation_count_dict[token] = 0

    total_gene_count = 0
    genome_count = 0
    gene_presence_total = Counter()
    gene_frequency_total = Counter()
    with open(infile, "r") as f1:
        while True:
            line = f1.readline()
            if not line:
                break
            genome_count += 1
            gene_presence_genome = {}

            line = line.rstrip().split("\t")[-1]

            split_line = line.split(" ")
            for gene in split_line:
                if gene != "_":
                    abs_gene_ID = abs(int(gene))
                    gene_ID = abs_gene_ID if absolute_IDs else int(gene)

                    # only count gene once per genome, ignore paralogs
                    gene_presence_genome[gene_ID] = 1

                    # count everything including paralogs
                    gene_frequency_total[gene_ID] += 1
                    total_gene_count += 1

            # merge dictionaries
            for gene_ID, entry in gene_presence_genome.items():
                gene_presence_total[gene_ID] += entry

                abs_gene_ID = abs(gene_ID)

                if abs_gene_ID in annotation_count_dict:
                    annotation_count_dict[abs_gene_ID] += entry
    
    # print to file
    with open(outpref + ".txt", "w") as o:
        o.write("Gene_ID\tGenome_count\tTotal_count\tGenome_freq\tTotal_freq\tTotal_genomes\tTotal_genes\n")
        for gene_ID, count in gene_presence_total.items():
            o.write("{}\t{}\t{}\t{}\t{}\t{}\t{}\n".format(gene_ID, count, gene_frequency_total[gene_ID], count/genome_count, gene_frequency_total[gene_ID]/total_gene_count, genome_count, total_gene_count))

    if annotations != None:
        with open(outpref + "_annotations.txt", "w") as o:
            for gene_ID, entry in annotation_dict.items():
                gene_count = annotation_count_dict[gene_ID]
                o.write(entry + "\t" + str(gene_count) + "\n")


if __name__ == "__main__":
    main()