import argparse
import re
from collections import defaultdict

def get_options():
    description = "Pull out genes that share at least one gene from annotations1 and annotations2"
    parser = argparse.ArgumentParser(description=description,
                                        prog='python find_concurrent_genes.py')
    IO = parser.add_argument_group('Input/options.out')
    IO.add_argument('--outpref',
                    default="comparisons",
                    help='Output prefix. Default = "comparisons"')
    IO.add_argument('--infile',
                    required=True,
                    help='Path to tokenised genome data .txt file.')
    IO.add_argument('--annotations1',
                    default=None,
                    help='First path to annotated tokens generated by annotate_tokens.py or calc_gene_frequency.py.')
    IO.add_argument('--annotations2',
                    default=None,
                    help='Second path to annotated tokens generated by annotate_tokens.py or calc_gene_frequency.py.')
    return parser.parse_args()

def get_annotations(annotations):
    annotation_set = set()
    with open(annotations, "r") as f1:
        while True:
            line = f1.readline()
            if not line:
                break
            line = line.rstrip()
            split_line = line.split("\t")
            token = abs(int(split_line[1]))

            annotation_set.add(token)
    
    return annotation_set

def main():
    options = get_options()
    infile = options.infile
    outpref = options.outpref
    annotations1 = options.annotations1
    annotations2 = options.annotations2
    
    # get token annotations
    annotation1_set = get_annotations(annotations1)
    annotation2_set = get_annotations(annotations2)
    
    concurrent_genome_dict = defaultdict(set)
    with open(infile, "r") as f1:
        while True:
            line = f1.readline()
            if not line:
                break

            stripped_line = line.rstrip().split("\t")
            genome_id = stripped_line[0]
            genome_entry = stripped_line[-1]

            split_line = genome_entry.split(" ")
            gene1 = None
            gene2 = None
            for gene in split_line:
                # determine if complete
                if gene1 != None and gene2 != None:
                    break

                if gene != "_":
                    abs_gene_ID = abs(int(gene))
                    
                    if abs_gene_ID in annotation1_set:
                        gene1 = abs_gene_ID
                    elif abs_gene_ID in annotation2_set:
                        gene2 = abs_gene_ID
            
            if gene1 != None and gene2 != None:
                identifier = f"{gene1}_{gene2}"

                concurrent_genome_dict[identifier].add(genome_id)

    for identifier, genome_id_set in concurrent_genome_dict.items():
        with open(f"{outpref}_geneids_{identifier}.txt", "w") as o:
            with open(infile, "r") as f1:
                while True:
                    line = f1.readline()
                    if not line:
                        break

                    stripped_line = line.rstrip().split("\t")
                    genome_id = stripped_line[0]

                    if genome_id in genome_id_set:
                        o.write(line)

if __name__ == "__main__":
    main()