import argparse
from collections import defaultdict
import random
import os
import math
import numpy as np
import pickle

def parse_args():
    """
    Parse command-line arguments.

    This function parses the command-line arguments provided by the user and returns
    a Namespace object containing the parsed arguments.
    """
    parser = argparse.ArgumentParser(description="Sample N genomes per cluster.")
    parser.add_argument("--clusters", type=str, required=True, help="Path to clusters file generated by PopPUNK.")
    parser.add_argument("--genomes", type=str, required=True, help="Path to tokenised genomes generated by tokenise_clusters.py. Must have genome per line with file name at beginning.")
    parser.add_argument("--n-genomes", type=int, default=1, help="Number of genomes to sample per cluster. Default = 1")
    parser.add_argument("--outpref", type=str, default="stratified_genomes", help="Output prefix. Default = stratified_genomes")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility")

    args = parser.parse_args()

    return args

def main():

    args = parse_args()
    clusters = args.clusters
    genomes = args.genomes
    n_genomes = args.n_genomes
    outpref = args.outpref
    seed = args.seed

    # set seed
    random.seed(seed)

    # hold set of genomes being analysed
    genome_set = set()
    with open(genomes, "r") as f:
            while True:
                line = f.readline()
                if not line:
                    break
                
                genome_id = os.path.splitext(line.rstrip().split("\t")[0])[0].split(".")[0]
                genome_set.add(genome_id)

    cluster_dict = defaultdict(list)
    with open(clusters, "r") as f:
        f.readline()
        for line in f:
            split_line = line.strip().split(",")
            
            # add genome to cluster entry if in dataset
            if split_line[0] in genome_set:
                cluster_dict[split_line[1]].append(split_line[0])


    # for each cluster, shuffle and randomly assign to sample
    sample_clusters = {}
    sample_genomes = set()
    for cluster in cluster_dict.keys():
        genome_list = cluster_dict[cluster]

        # calculate number of genomes to move and then shuffle
        random.shuffle(genome_list)

        # create new cluster list
        sample_clusters[cluster] = genome_list[:n_genomes]
        sample_genomes.update(genome_list[:n_genomes])

    # sample genomes from input file
    with open(outpref + "_genomes.txt", 'w') as o:
        with open(genomes, "r") as f:
            while True:
                line = f.readline()
                if not line:
                    break
                
                genome_id = os.path.splitext(line.rstrip().split("\t")[0])[0].split(".")[0]

                if genome_id in sample_genomes:
                    o.write(line)
    
    # write clusters out
    with open(outpref + "_clusters.txt", 'w') as o:
        header = "Taxon,Cluster\n"
        o.write(header)

        for cluster, genome_list in sample_clusters.items():
            for genome in genome_list:
                o.write(f"{genome},{cluster}\n")
                
if __name__ == "__main__":
    main()