library(ggplot2)
library(ggsci)
library(optparse)

option_list <- list(
  make_option("--infile", type="character", help="Path to parsed training log file generated by parse_training_log.py."),
  make_option("--outpref", type="character", default="output", help="Output prefix for saved plots. Default = 'output'")
)
opt <- parse_args(OptionParser(option_list=option_list))

df<-read.csv(opt$infile, sep = "\t", header = 1)

data_subset = subset(df, Type != "Test")
p <- ggplot(data_subset, aes(x = Epoch, y=Loss, colour = Type)) +
  geom_line(linewidth=1.5) +
  scale_colour_npg() +
  theme_light() +
  theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), axis.title=element_text(size=16,face="bold"), legend.title=element_text(size=16,face="bold"), legend.text=element_text(size=14)) +
  guides(colour=guide_legend(title="Data type")) +
  scale_y_log10() +
  labs(x = "Epoch", y = "Cross Entropy Loss")
p
ggsave(file=paste0(opt$outpref, "_loss.svg"), plot=p, height = 6, width = 8)
ggsave(file=paste0(opt$outpref, "_loss.png"), plot=p, height = 6, width = 8)

p <- ggplot(data_subset, aes(x = Epoch, y=Precision, colour = Type)) +
  geom_line(linewidth=1.5) +
  scale_colour_npg() +
  theme_light() +
  theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), axis.title=element_text(size=16,face="bold"), legend.title=element_text(size=16,face="bold"), legend.text=element_text(size=14), legend.position = "none") +
  guides(colour=guide_legend(title="Data type")) +
  labs(x = "Epoch", y = "Precision")
p
ggsave(file=paste0(opt$outpref, "_precision.svg"), plot=p, height = 6, width = 8)
ggsave(file=paste0(opt$outpref, "_precision.png"), plot=p, height = 6, width = 8)

p <- ggplot(data_subset, aes(x = Epoch, y=Recall, colour = Type)) +
  geom_line(linewidth=1.5) +
  scale_colour_npg() +
  theme_light() +
  theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), axis.title=element_text(size=16,face="bold"), legend.title=element_text(size=16,face="bold"), legend.text=element_text(size=14), legend.position = "none") +
  guides(colour=guide_legend(title="Data type")) +
  labs(x = "Epoch", y = "Recall")
p
ggsave(file=paste0(opt$outpref, "_recall.svg"), plot=p, height = 6, width = 8)
ggsave(file=paste0(opt$outpref, "_recall.png"), plot=p, height = 6, width = 8)

p <- ggplot(data_subset, aes(x = Epoch, y=Kappa, colour = Type)) +
  geom_line(linewidth=1.5) +
  scale_colour_npg() +
  theme_light() +
  theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), axis.title=element_text(size=16,face="bold"), legend.title=element_text(size=16,face="bold"), legend.text=element_text(size=14), legend.position = "none") +
  guides(colour=guide_legend(title="Data type")) +
  labs(x = "Epoch", y = "Cohen's Kappa")
p
ggsave(file=paste0(opt$outpref, "_kappa.svg"), plot=p, height = 6, width = 8)
ggsave(file=paste0(opt$outpref, "_kappa.png"), plot=p, height = 6, width = 8)
